export const articles_list = [
    {
      id: 1,
      heading: "7 Best React Project Ideas For Beginners in 2022",
      sub_head: "If you’re one of those who want to have some cool projects on React, here’s an amazing journey that will tell you some of the brilliant ideas. For working with some applications or websites, you need to have a good knowledge of JavaScript.",
      img_url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20220310072422/7-Best-React-Project-Ideas-for-Beginners-in-2022.png",
      arti_link: "https://www.geeksforgeeks.org/7-best-react-project-ideas-for-beginners-in-2022/?ref=gcse",
    },
    {
      id: 2,
      heading: "7 Project Ideas on Blockchain For Professionals",
      sub_head: "We have passed the time when blockchain was used only in the form of cryptocurrency. Today, it is being used in a broader domain and it’s going to dominate in the coming future.",
      img_url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20220314001728/7-Project-Ideas-on-Blockchain-For-Professionals.png",
      arti_link: "https://www.geeksforgeeks.org/7-project-ideas-on-blockchain-for-professionals/",
    },
    {
      id: 3,
      heading: "Top 5 Skills You Must Know Before You Learn ReactJS",
      sub_head: "In React you will work with JSX that looks like HTML and you can consider it like HTML-flavored JavaScript. It is the easiest way to add HTML code inside javascript or you can say it is the extension of the Javascript language syntax.",
      img_url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20191231190155/Top-7-Skills-You-Must-Know-Before-You-Learn-ReactJS.png",
      arti_link: "https://www.geeksforgeeks.org/top-5-skills-you-must-know-before-you-learn-reactjs/?ref=gcse",
    },
    {
      id: 4,
      heading: "5 Must-Have Skills You’ll Need In Your Hackathon Team",
      sub_head: "What are the Hackathons? In general, Hackathons are the programming competitions where you’re required to provide an optimal & impactful solution for a real-world problem. You’re usually required to come up with a team of around 2-6 members",
      img_url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20200814212006/5-Must-Have-Skills-You%E2%80%99ll-Need-In-Your-Hackathon-Team.png",
      arti_link: "https://www.geeksforgeeks.org/5-must-have-skills-youll-need-in-your-hackathon-team/?ref=gcse",
    },
    {
      id: 5,
      heading: "5 Reasons Why Hackathons are Important in a Coder’s Life",
      sub_head: "Before beginning the blog and discussing the very question, let us first understand what a hackathon is – Hackathons are competitions where one tries to make something be it software, hardware or something else at all to provide an impactful solution to a given problem statement by the hackathon organizers in most cases.",
      img_url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20200422222745/5-Reasons-Why-Hackathons-are-Important-in-a-Coder%E2%80%99s-Life.png",
      arti_link: "https://www.geeksforgeeks.org/5-reasons-why-hackathons-are-important-in-a-coders-life/?ref=gcse",
    },
    {
      id: 6,
      heading: "6 Weeks of Android App Development – FREE Project Based Learning",
      sub_head: "Are you among the ones who want to learn Android App Development from the beginning? Are you someone who doesn’t have any idea about Android App Development? Or you have just started your journey, but you don’t know whether you are on the right path or not.",
      img_url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20210918185215/6-Weeks-of-Android-App-Development-FREE-Project-Based-Learning.png",
      arti_link: "https://www.geeksforgeeks.org/6-weeks-of-android-app-development-free-project-based-learning/?ref=gcse",
    },
    {
      id: 7,
      heading: "Top 10 Machine Learning Project Ideas That You Can Implement",
      sub_head: "Machine Learning is one of the most popular emerging technologies in current times! And the best way to learn this technology is by doing projects. Other options like online courses, reading books, etc. only help in understanding the basics of ML, but",
      img_url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20200811224321/Top-10-Machine-Learning-Project-Ideas-That-You-Can-Implement.png",
      arti_link: "https://www.geeksforgeeks.org/top-10-machine-learning-project-ideas-that-you-can-implement/?ref=gcse",
    },
    {
      id: 8,
      heading: "Top 7 Java Project Ideas To Enhance Programming Skills",
      sub_head: "As a beginner, you’re strongly recommended to start your project building journey with this classic Snake game as it will help you to maintain interest and curiosity throughout the project. The snake game can be created in different ways & with different rules – however",
      img_url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20201119221149/Top-7-Java-Project-Ideas-To-Enhance-Programming-Skills-%E2%80%93-Beginner-to-Advanced-Level.png",
      arti_link: "https://www.geeksforgeeks.org/top-7-java-project-ideas-to-enhance-programming-skills/?ref=gcse",
    },
    {
      id: 9,
      heading: "7 Cool Python Project Ideas for Intermediate Developers",
      sub_head: "Python in the world of programming everyone is familiar with the popularity of this language. Learning python and building the project is always an amazing experience for developers. This language really deserves hype in today’s era and why not if it can solve a lot of real-world problems.",
      img_url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20200602220541/7-Cool-Python-Project-Ideas-for-Intermediate-Developers.png",
      arti_link: "https://www.geeksforgeeks.org/7-cool-python-project-ideas-for-intermediate-developers/?ref=gcse",
    },
    {
      id: 10,
      heading: "Top 10 Projects For Beginners To Practice HTML and CSS Skills",
      sub_head: "Learning to code is always exciting and fun for everyone and when it comes to stepping into the programming world most of the people start with the easiest thing HTML and CSS. Every beginner’s coding journey in frontend starts with these two basic building blocks",
      img_url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20200121234029/Top-10-Projects-For-Beginners-To-Practice-HTML-and-CSS-Skills.jpg",
      arti_link: "https://www.geeksforgeeks.org/top-10-projects-for-beginners-to-practice-html-and-css-skills/?ref=gcse",
    },
    {
      id: 11,
      heading: "10 Best Angular Projects Ideas For Beginners",
      sub_head: "Angular Project Ideas are bringing revolution to many sectors like healthcare, manufacturing, finance, and so on. This is because those ideas are full of encouragement and efficiency as they aren’t only time-saving but resourceful too.",
      img_url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20210812200656/10-Best-Angular-Projects-Ideas-For-Beginners-in-2021.png",
      arti_link: "https://www.geeksforgeeks.org/10-best-angular-projects-ideas-for-beginners/?ref=gcse",
    },
    {
      id: 12,
      heading: "How to Publish a Static Website on GitHub?",
      sub_head: "Git is a free and distributed version-control system for tracking changes in source code during software development. It is designed for coordinating work among programmers, but it can be used to track changes in any set of files.",
      img_url: "https://media.geeksforgeeks.org/wp-content/uploads/20200707144129/SigninGitAcc.png",
      arti_link: "https://www.geeksforgeeks.org/how-to-publish-a-static-website-on-github/?ref=gcse",
    },
    {
      id: 13,
      heading: "Top 7 Database You Must Know For Software Development Projects",
      sub_head: "A database is just like a room in an office where all the files and important information can be stored related to a project. Every company needs a database to store and organize the information. The information that we store can be very sensitive so we always have to be careful while accessing or manipulating the information in the database.",
      img_url: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20200106002909/Top-7-Database-You-Must-Know-For-Software-Development-Projects.png",
      arti_link: "https://www.geeksforgeeks.org/top-7-database-you-must-know-for-software-development-projects/?ref=gcse",
    },
  ];
  